# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - api-movieactorranking-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tonylukeregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_463c159039f44942b5dcddf84c99affb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b0d647edcf2249d589877ccbe9f69126 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_463c159039f44942b5dcddf84c99affb }}/movie-actor-ranking/api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-movieactorranking-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_90bc298aa4c747fc9158fe60c0247d34 }}
        images: 'tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_463c159039f44942b5dcddf84c99affb }}/movie-actor-ranking/api:${{ github.sha }}'